name: Python Release

on:
  workflow_dispatch: {}

jobs:
  python-build:
    name: Build for PyPi
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      contents: read

    defaults:
      run:
        working-directory: ./tools/python

    steps:
      - name: Checkout
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5

      - name: Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@6dfebec6ddbcd197e02256fbdf54deb334fb7f06 # v2

      - name: Install
        run: make venv

      - name: Build
        run: |
          set -x
          source .venv/bin/activate
          rm -rf build dist *.egg-info
          make build
          python -m twine check dist/*

      - name: Test
        run: |
          make venv
          make test

      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: release-dists
          path: ./tools/python/dist/

  python-release:
    name: Publish to PyPi
    runs-on: ubuntu-latest
    environment: pypi
    needs:
      - python-build

    defaults:
      run:
        working-directory: ./tools/python

    permissions:
      id-token: write

    steps:
      - name: Retrieve distribution
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: release-dists
          path: dist/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # release/v1
