#!/usr/bin/env python3
"""Generates a README.md with stats about all skills repos in the skills/ folder."""

import os
import subprocess
import json
from datetime import datetime, timezone
from pathlib import Path

SKILLS_DIR = Path(__file__).parent / "skills"
README_PATH = Path(__file__).parent / "README.md"

REPOS = [
    {
        "url": "https://github.com/slavingia/skills",
        "dir": "skills",
        "description": "Claude Code skills by Sahil Lavingia",
    },
    {
        "url": "https://github.com/zarazhangrui/codebase-to-course",
        "dir": "codebase-to-course",
        "description": "Turn any codebase into a structured course",
    },
    {
        "url": "https://github.com/samber/cc-skills-golang",
        "dir": "cc-skills-golang",
        "description": "Claude Code skills for Go development",
    },
]


def run(cmd, cwd=None):
    result = subprocess.run(cmd, capture_output=True, text=True, cwd=cwd, timeout=60)
    return result.stdout.strip()


def get_latest_commit(repo_path):
    if not repo_path.exists():
        return None, None, None
    sha = run(["git", "log", "-1", "--format=%H"], cwd=repo_path)
    date = run(["git", "log", "-1", "--format=%aI"], cwd=repo_path)
    msg = run(["git", "log", "-1", "--format=%s"], cwd=repo_path)
    return sha[:10] if sha else "n/a", date or "n/a", msg or "n/a"


def count_skill_files(repo_path):
    """Count .md files that look like skill definitions."""
    if not repo_path.exists():
        return 0
    count = 0
    for f in repo_path.rglob("*.md"):
        # Skip common non-skill markdown files
        if f.name.lower() in ("readme.md", "license.md", "changelog.md", "contributing.md"):
            continue
        count += 1
    return count


def get_star_count(url):
    """Try to get star count via gh CLI."""
    repo_slug = url.replace("https://github.com/", "")
    try:
        out = run(["gh", "repo", "view", repo_slug, "--json", "stargazerCount"])
        if out:
            data = json.loads(out)
            return data.get("stargazerCount", "?")
    except Exception:
        pass
    return "?"


def sync_repos():
    """Clone or pull all repos."""
    SKILLS_DIR.mkdir(exist_ok=True)
    for repo in REPOS:
        repo_path = SKILLS_DIR / repo["dir"]
        if repo_path.exists():
            print(f"Pulling {repo['dir']}...")
            run(["git", "pull", "--ff-only"], cwd=repo_path)
        else:
            print(f"Cloning {repo['url']}...")
            run(["git", "clone", repo["url"], str(repo_path)])


def generate_readme():
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    total_skills = 0
    rows = []

    for repo in REPOS:
        repo_path = SKILLS_DIR / repo["dir"]
        sha, date, msg = get_latest_commit(repo_path)
        skills_count = count_skill_files(repo_path)
        stars = get_star_count(repo["url"])
        total_skills += skills_count

        if date and date != "n/a":
            try:
                dt = datetime.fromisoformat(date)
                date = dt.strftime("%Y-%m-%d")
            except ValueError:
                pass

        rows.append(
            f"| [{repo['dir']}]({repo['url']}) | {repo['description']} "
            f"| {skills_count} | {stars} | `{sha}` | {date} | {msg} |"
        )

    table = "\n".join(rows)

    readme = f"""\
# Skills Collection

A curated collection of Claude Code skills repos, automatically synced every 2 days.

## Stats

| | |
|---|---|
| **Total repos** | {len(REPOS)} |
| **Total skill files** | {total_skills} |
| **Last synced** | {now} |

## Repos

| Repo | Description | Skills | Stars | Latest Commit | Date | Message |
|------|-------------|--------|-------|---------------|------|---------|
{table}

## How it works

A GitHub Actions workflow runs every 2 days to:

1. Clone or pull all skill repos into `skills/`
2. Run `generate_readme.py` to regenerate this README with fresh stats
3. Commit and push any changes

---

*Auto-generated by `generate_readme.py` on {now}*
"""

    README_PATH.write_text(readme)
    print(f"README.md generated ({total_skills} skill files across {len(REPOS)} repos)")


if __name__ == "__main__":
    sync_repos()
    generate_readme()
