#!/usr/bin/env bash
#===============================================================================
# Receipt-Gated Deploy Tests
#
# `loki deploy --execute` runs a deploy command ONLY when a VERIFIED Evidence
# Receipt authorizes THIS tree. This suite proves the gate holds in both
# directions: it refuses everything it should, AND it still executes when the
# evidence is genuinely good.
#
# WHY TEST 8 (the positive control) IS MANDATORY. A gate that refuses every
# input passes tests 2-7 perfectly while being completely broken. Test 8 is the
# only case that cannot pass by refusing, so it is what makes the other seven
# mean anything. If test 8 ever goes red, the feature is dead regardless of how
# green the refusals look.
#
# WHY TEST 3 (tampered) IS LOAD-BEARING. It is the case where an attacker has
# write access to the receipt -- the exact scenario the evidence layer exists to
# detect. A gate that accepts a rewritten receipt is not a gate.
#
# NO CLOUD CLI IS EVER RUN. The deploy CLIs are stubs on a controlled PATH; each
# writes a sentinel file IF executed. That makes NON-execution assertable
# (sentinel absent) and execution assertable (sentinel present) using the same
# mechanism, so neither direction can pass vacuously. Mirrors tests/test-deploy.sh.
#
# Receipts are built by the REAL generator (autonomy/lib/proof-generator.py) so
# the integrity hash is genuine -- a hand-written proof.json would fail hash_ok
# and make every test pass for the wrong reason.
#===============================================================================

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
LOKI_BIN="$PROJECT_DIR/autonomy/loki"
GENERATOR="$PROJECT_DIR/autonomy/lib/proof-generator.py"

PASS=0
FAIL=0
ok()  { PASS=$((PASS + 1)); echo "  PASS: $1"; }
bad() { FAIL=$((FAIL + 1)); echo "  FAIL: $1"; [ -n "${2:-}" ] && echo "        $2"; }

echo "TEST: loki deploy --execute is gated on a verified Evidence Receipt"
echo "==================================================================="
echo ""

[ -f "$LOKI_BIN" ]   || { echo "  FAIL: $LOKI_BIN missing"; exit 1; }
[ -f "$GENERATOR" ]  || { echo "  FAIL: $GENERATOR missing"; exit 1; }
command -v python3 >/dev/null 2>&1 || { echo "  SKIPPED: python3 not installed (not a pass)"; exit 0; }
command -v git     >/dev/null 2>&1 || { echo "  SKIPPED: git not installed (not a pass)"; exit 0; }

WORKROOT="$(mktemp -d "${TMPDIR:-/tmp}/loki-deploygate.XXXXXX")"
cleanup() { rm -rf "$WORKROOT" 2>/dev/null || true; }
trap cleanup EXIT INT TERM

# --- stub deploy CLIs -------------------------------------------------------
# Sentinel-on-execution. Never a real cloud call.
FAKE_BIN="$WORKROOT/fake-bin"
SENTINEL_DIR="$WORKROOT/sentinels"
mkdir -p "$FAKE_BIN" "$SENTINEL_DIR"
for cli in vercel netlify flyctl wrangler; do
    cat > "$FAKE_BIN/$cli" <<EOF
#!/usr/bin/env bash
echo "STUB-RAN \$*" > "$SENTINEL_DIR/$cli"
exit 0
EOF
    chmod +x "$FAKE_BIN/$cli"
done
reset_sentinels() { rm -f "$SENTINEL_DIR"/* 2>/dev/null || true; }
# Counts sentinel files with a glob rather than `ls | grep` (SC2010): ls parses
# badly on names with spaces or newlines, and a stub CLI is free to write one.
any_sentinel()    { local _f _n=0; for _f in "$SENTINEL_DIR"/*; do [ -e "$_f" ] && _n=$((_n+1)); done; printf '%s' "$_n"; }

# --- fixture builder --------------------------------------------------------
# A git repo with >=2 commits (so base..head is real sha algebra, not the
# greenfield empty-tree case resolve_anchor rejects), a deployable project type,
# and a genuine receipt generated by the real generator.
#
# _LOKI_RUN_START_SHA is what the generator reads for base_sha, so it is set to
# the first commit: the receipt then records base..head spanning exactly the
# second commit's file set, which is what resolve_anchor demands.
make_fixture() {
    local name="$1"
    local d="$WORKROOT/$name"
    mkdir -p "$d"
    git -C "$d" init -q .
    git -C "$d" config user.email "test@example.com"
    git -C "$d" config user.name  "test"
    git -C "$d" config commit.gpgsign false

    # Commit 1: baseline. .loki/ is gitignored exactly as the real repo does
    # (see .gitignore:43) -- receipt generation writes .loki/proofs/, and if that
    # counted as a dirty tree then producing a receipt would make every deploy
    # refuse itself. The fixture must mirror production here or test 8 is
    # impossible for a reason that does not exist in the field.
    echo "# fixture" > "$d/README.md"
    printf '.loki/\n' > "$d/.gitignore"
    git -C "$d" add README.md .gitignore
    git -C "$d" commit -qm "baseline"
    local base
    base="$(git -C "$d" rev-parse HEAD)"

    # Commit 2: the deployable project. A Next.js app is used deliberately: its
    # idiomatic command is "vercel --prod", which carries NO <placeholder>. A
    # Vite/static fixture yields "netlify deploy --prod --dir=<build-output>",
    # which the gate correctly refuses as unfilled -- so it could never reach
    # the positive control.
    cat > "$d/package.json" <<'PKG'
{ "name": "fixture-app", "version": "1.0.0", "dependencies": { "next": "^14.0.0" } }
PKG
    git -C "$d" add package.json
    git -C "$d" commit -qm "add app"

    printf '%s' "$base"
}

# Generate a REAL receipt for the fixture's current HEAD.
# The generator reads the TARGET FROM CWD (it has no --target-dir flag), so the
# cd is load-bearing, not cosmetic.
gen_receipt() {
    local d="$1" base="$2"
    ( cd "$d" && _LOKI_RUN_START_SHA="$base" \
        python3 "$GENERATOR" --loki-dir "$d/.loki" >/dev/null 2>&1 )
    ls -d "$d"/.loki/proofs/*/ 2>/dev/null | head -1
}

# Run `loki deploy` against a fixture under the stub PATH.
run_deploy() {
    local d="$1"; shift
    ( cd "$d" && PATH="$FAKE_BIN:$PATH" LOKI_DIR="$d/.loki" \
        bash "$LOKI_BIN" deploy --dir "$d" --no-clip "$@" 2>&1 )
}

# ---------------------------------------------------------------------------
# Preflight: the generator must actually produce a receipt, or every downstream
# assertion is vacuous. This is checked LOUDLY rather than assumed.
# ---------------------------------------------------------------------------
PRE_BASE="$(make_fixture preflight)"
PRE_DIR="$WORKROOT/preflight"
PRE_PROOF="$(gen_receipt "$PRE_DIR" "$PRE_BASE")"
if [ -n "$PRE_PROOF" ] && [ -f "$PRE_PROOF/proof.json" ]; then
    echo "  (preflight: real receipt generated at $(basename "$PRE_PROOF"))"
else
    echo "  FAIL: could not generate a receipt; the suite would pass vacuously"
    exit 1
fi
echo ""

# ===========================================================================
# 1. DEFAULT (no --execute) still prints and does NOT execute.
#    The existing behaviour must not regress.
# ===========================================================================
echo "1. default (no --execute) prints, never executes"
D1_BASE="$(make_fixture d1)"; D1="$WORKROOT/d1"
gen_receipt "$D1" "$D1_BASE" >/dev/null
reset_sentinels
OUT1="$(run_deploy "$D1")"
if [ "$(any_sentinel)" -eq 0 ] && printf '%s' "$OUT1" | grep -q "vercel --prod"; then
    ok "prints the deploy command and runs no CLI"
else
    bad "default path executed a CLI or printed nothing" "sentinels=$(any_sentinel)"
fi
# The stronger half of this assertion (the default path must not deploy even a
# VERIFIED tree) needs the signed fixture from test 8, so it runs as test 10.

# ===========================================================================
# 2. --execute with NO receipt refuses, and NAMES that as the reason.
# ===========================================================================
echo "2. --execute with no receipt refuses"
make_fixture d2 >/dev/null; D2="$WORKROOT/d2"   # deliberately no gen_receipt
reset_sentinels
OUT2="$(run_deploy "$D2" --execute)"
if [ "$(any_sentinel)" -eq 0 ] \
   && printf '%s' "$OUT2" | grep -qi "REFUSED" \
   && printf '%s' "$OUT2" | grep -qi "no Evidence Receipt"; then
    ok "refuses and names the missing receipt"
else
    bad "did not refuse, or did not name the missing receipt" "sentinels=$(any_sentinel)"
fi

# ===========================================================================
# 3. THE LOAD-BEARING TEST: a TAMPERED receipt refuses.
#    The receipt is real, then its recorded facts are rewritten WITHOUT
#    recomputing the hash -- exactly the edit VERIFICATION-COST.md documents as
#    detectable.
# ===========================================================================
echo "3. --execute with a TAMPERED receipt refuses"
D3_BASE="$(make_fixture d3)"; D3="$WORKROOT/d3"
P3="$(gen_receipt "$D3" "$D3_BASE")"
python3 -c "
import json,sys
p = sys.argv[1]
d = json.load(open(p))
d['files_changed'] = {'count': 999999}
json.dump(d, open(p,'w'))
" "$P3/proof.json"
reset_sentinels
OUT3="$(run_deploy "$D3" --execute)"
if [ "$(any_sentinel)" -eq 0 ] \
   && printf '%s' "$OUT3" | grep -qi "REFUSED" \
   && printf '%s' "$OUT3" | grep -qi "TAMPERED"; then
    ok "refuses a receipt whose hash no longer matches its contents"
else
    bad "a TAMPERED receipt authorized a deploy" "sentinels=$(any_sentinel)"
fi

# ===========================================================================
# 4. An UNSIGNED receipt refuses. Integrity is not provenance.
#    The default generator path is unsigned, so this is the common real case.
# ===========================================================================
echo "4. --execute with an UNSIGNED receipt refuses"
D4_BASE="$(make_fixture d4)"; D4="$WORKROOT/d4"
gen_receipt "$D4" "$D4_BASE" >/dev/null
reset_sentinels
OUT4="$(run_deploy "$D4" --execute)"
if [ "$(any_sentinel)" -eq 0 ] \
   && printf '%s' "$OUT4" | grep -qi "REFUSED" \
   && printf '%s' "$OUT4" | grep -qi "UNSIGNED"; then
    ok "refuses an unsigned receipt (integrity is not provenance)"
else
    bad "an UNSIGNED receipt authorized a deploy" "sentinels=$(any_sentinel)"
fi

# ===========================================================================
# 5. A receipt for a DIFFERENT commit refuses.
#    The receipt is genuine and its hash is intact -- only the tree has moved
#    on. This is the stale-receipt case: resolve_anchor alone reports "anchored"
#    for an ancestor commit (measured), so the head_sha == live HEAD check is
#    what catches it.
# ===========================================================================
echo "5. --execute with a receipt for a different commit refuses"
D5_BASE="$(make_fixture d5)"; D5="$WORKROOT/d5"
gen_receipt "$D5" "$D5_BASE" >/dev/null
echo "later change" > "$D5/extra.txt"
git -C "$D5" add extra.txt
git -C "$D5" commit -qm "move past the receipt"
reset_sentinels
OUT5="$(run_deploy "$D5" --execute)"
if [ "$(any_sentinel)" -eq 0 ] \
   && printf '%s' "$OUT5" | grep -qi "REFUSED" \
   && printf '%s' "$OUT5" | grep -qiE "different commit|does not anchor"; then
    ok "refuses a receipt that records a commit other than HEAD"
else
    bad "a stale receipt authorized deploying a tree it never verified" "sentinels=$(any_sentinel)"
fi

# ===========================================================================
# 6. A DIRTY working tree refuses.
#    Deploying bytes other than the verified ones is the exact failure this
#    feature prevents.
# ===========================================================================
echo "6. --execute with a dirty working tree refuses"
D6_BASE="$(make_fixture d6)"; D6="$WORKROOT/d6"
gen_receipt "$D6" "$D6_BASE" >/dev/null
echo "uncommitted" >> "$D6/package.json"
reset_sentinels
OUT6="$(run_deploy "$D6" --execute)"
if [ "$(any_sentinel)" -eq 0 ] \
   && printf '%s' "$OUT6" | grep -qi "REFUSED" \
   && printf '%s' "$OUT6" | grep -qi "dirty"; then
    ok "refuses a dirty tree and names it"
else
    bad "a dirty tree was deployed" "sentinels=$(any_sentinel)"
fi

# ===========================================================================
# 7. A DESTRUCTIVE command is refused even with a valid receipt.
#    The canonical command table contains nothing destructive, so the detector
#    is driven DIRECTLY. Extracted to a file and SOURCED rather than eval'd --
#    the repo's own quality gate flags an eval form as a HIGH finding
#    (see tests/test-verify-runner-selection.sh).
# ===========================================================================
echo "7. destructive commands are refused even with a valid receipt"
DESTRUCT_FN="$WORKROOT/destructive.sh"
sed -n '/^_deploy_is_destructive()/,/^}/p' "$LOKI_BIN" > "$DESTRUCT_FN"
if [ ! -s "$DESTRUCT_FN" ]; then
    bad "could not extract _deploy_is_destructive from $LOKI_BIN"
else
    # shellcheck disable=SC1090
    . "$DESTRUCT_FN"
    _d_ok=0; _d_bad=0
    for c in "vercel remove my-app" "fly apps destroy prod" "wrangler delete" \
             "kubectl delete deployment web" "terraform destroy" "heroku apps:destroy"; do
        if _deploy_is_destructive "$c"; then _d_ok=$((_d_ok+1)); else _d_bad=$((_d_bad+1)); echo "        missed: $c"; fi
    done
    # NON-VACUITY: the legitimate deploy commands must NOT be flagged, or the
    # detector could "pass" by calling everything destructive and the positive
    # control in test 8 would be impossible.
    _d_false=0
    for c in "vercel --prod" "netlify deploy --prod --dir=dist" "fly deploy" \
             "wrangler pages deploy dist" "wrangler deploy"; do
        if _deploy_is_destructive "$c"; then _d_false=$((_d_false+1)); echo "        false positive: $c"; fi
    done
    if [ "$_d_bad" -eq 0 ] && [ "$_d_false" -eq 0 ]; then
        ok "all $_d_ok destructive forms refused; no legitimate deploy command flagged"
    else
        bad "destructive detection wrong (missed=$_d_bad false-positives=$_d_false)"
    fi
fi

# ===========================================================================
# 7b. A command with an UNFILLED <placeholder> is refused.
#     "netlify deploy --prod --dir=<build-output>" is written for a human to
#     complete. Running it verbatim is a shell syntax error, and "<" would be a
#     REDIRECTION -- so this must refuse rather than execute or guess a value.
#     Driven with a Vite fixture, whose idiomatic command carries the placeholder.
# ===========================================================================
echo "7b. an unfilled <placeholder> command is refused, never guessed"
D7B_BASE="$(make_fixture d7b)"; D7B="$WORKROOT/d7b"
cat > "$D7B/package.json" <<'PKG'
{ "name": "vite-app", "version": "1.0.0", "devDependencies": { "vite": "^5.0.0" } }
PKG
git -C "$D7B" add package.json
git -C "$D7B" commit -qm "switch to vite (placeholder command)"
gen_receipt "$D7B" "$D7B_BASE" >/dev/null
reset_sentinels
OUT7B="$(run_deploy "$D7B" --execute)"
if [ "$(any_sentinel)" -eq 0 ] \
   && printf '%s' "$OUT7B" | grep -qi "REFUSED" \
   && printf '%s' "$OUT7B" | grep -qi "placeholder"; then
    ok "refuses an unfilled placeholder command instead of running or guessing it"
else
    bad "a <placeholder> command was executed or refused for the wrong reason" "sentinels=$(any_sentinel)"
fi

# ===========================================================================
# 8. POSITIVE CONTROL: a VERIFIED receipt on a clean, matching tree EXECUTES.
#    Without this the gate could score a perfect 7/7 above by refusing
#    everything, which is a broken feature that looks fully tested.
#
#    Signing needs gpg + a key. Rather than depend on the host keyring, the
#    VERIFIED verdict is produced by driving _deploy_receipt_verdict's inputs:
#    we assert the gate's OTHER three checks (receipt present, anchored, clean)
#    all pass on a genuine receipt, and that the ONLY thing standing between
#    this tree and execution is the signature. That is asserted by observing
#    UNSIGNED as the SOLE refusal reason -- proving anchor + cleanliness passed.
#    Then, with gpg available, the full signed path is exercised end to end.
# ===========================================================================
echo "8. POSITIVE CONTROL: a good receipt on a clean matching tree executes"
D8_BASE="$(make_fixture d8)"; D8="$WORKROOT/d8"
gen_receipt "$D8" "$D8_BASE" >/dev/null
reset_sentinels
OUT8="$(run_deploy "$D8" --execute)"
# The anchor and clean-tree checks must PASS here: the only refusal is signing.
if printf '%s' "$OUT8" | grep -qi "UNSIGNED" \
   && ! printf '%s' "$OUT8" | grep -qiE "dirty|does not anchor|different commit|no Evidence Receipt"; then
    ok "anchor + clean-tree checks PASS on a good tree (only the signature blocks)"
else
    bad "a good tree failed a check other than signing -- the gate refuses everything" \
        "$(printf '%s' "$OUT8" | grep -i ' - ' | head -4)"
fi

# The full execute path, with a real signature.
if command -v gpg >/dev/null 2>&1; then
    GNUPGHOME="$WORKROOT/gnupg"; export GNUPGHOME
    mkdir -p "$GNUPGHOME"; chmod 700 "$GNUPGHOME"
    cat > "$WORKROOT/keyparams" <<'KEY'
%no-protection
Key-Type: eddsa
Key-Curve: ed25519
Name-Real: Loki Deploy Gate Test
Name-Email: deploy-gate@example.invalid
Expire-Date: 0
%commit
KEY
    if gpg --batch --gen-key "$WORKROOT/keyparams" >/dev/null 2>&1; then
        KEYID="$(gpg --list-secret-keys --with-colons 2>/dev/null | awk -F: '/^sec:/{print $5; exit}')"
        D9_BASE="$(make_fixture d8signed)"; D8S="$WORKROOT/d8signed"
        ( cd "$D8S" && _LOKI_RUN_START_SHA="$D9_BASE" \
            LOKI_PROOF_GPG_KEY="$KEYID" GNUPGHOME="$GNUPGHOME" \
            python3 "$GENERATOR" --loki-dir "$D8S/.loki" >/dev/null 2>&1 )
        reset_sentinels
        OUT8S="$( cd "$D8S" && PATH="$FAKE_BIN:$PATH" LOKI_DIR="$D8S/.loki" GNUPGHOME="$GNUPGHOME" \
            bash "$LOKI_BIN" deploy --dir "$D8S" --no-clip --execute 2>&1 )"
        if [ "$(any_sentinel)" -ge 1 ] && printf '%s' "$OUT8S" | grep -qi "gate PASSED"; then
            # Records that a deploy REALLY executed, so test 9 can tell a genuine
            # skip (no signed path available) from a missing record (a defect).
            D8S_EXECUTED=1
            ok "a VERIFIED receipt on a clean matching tree DOES execute the deploy"
            # The printed prose must not contradict what happens next. The
            # advisory's closing line is "Loki does not deploy for you", which is
            # true on the print-only path and FALSE printed immediately above a
            # deploy that then runs.
            if printf '%s' "$OUT8S" | grep -qi "Loki does not deploy for you"; then
                bad "printed 'Loki does not deploy for you' and then deployed"
            else
                ok "the executing run does not print the print-only claim"
            fi
        else
            bad "a fully verified receipt did NOT execute" \
                "sentinels=$(any_sentinel); $(printf '%s' "$OUT8S" | grep -i ' - ' | head -3)"
        fi
    else
        echo "  SKIPPED: gpg key generation failed (signed path unproven, not a pass)"
    fi
else
    echo "  SKIPPED: gpg not installed (signed execute path unproven, not a pass)"
fi

# The positive control is the ONE case that cannot pass by refusing, so a run
# that never executed it has not tested the gate -- it has only watched it say
# no. Printing "SKIPPED (not a pass)" does not reach the EXIT CODE, so without
# this the whole suite goes green on a host with no gpg, with the load-bearing
# test and both non-vacuity guards silently absent. That is the same false-green
# fixed inside test 9, one level up.
if [ "${D8S_EXECUTED:-0}" != "1" ]; then
    bad "POSITIVE CONTROL DID NOT RUN: no deploy was ever executed, so nothing here proves the gate can say yes" \
        "install gpg to prove the signed execute path; a suite of refusals alone is not a passing gate"
fi

# ===========================================================================
# 9. An executed deploy WRITES A RECORD naming the authorizing run_id.
#    A deploy with no record of itself defeats the premise of gating on
#    evidence. Reuses the signed fixture from test 8 when it executed.
# ===========================================================================
echo "9. an executed deploy records the authorizing run_id"
# The skip condition is DELIBERATELY keyed on "did a deploy execute", NOT on
# "does .loki/deploys exist". Keying it on the directory made deleting the
# record-writing code produce a SKIP and a green suite -- the mutation that was
# supposed to go red instead made the test disappear. A missing directory after
# a successful execute is now the FAILURE it actually is.
if [ -n "${D8S:-}" ] && [ "${D8S_EXECUTED:-0}" = "1" ]; then
    REC="$(ls -1 "$D8S"/.loki/deploys/*.json 2>/dev/null | head -1)"
    if [ -n "$REC" ]; then
        RUN_IN_RECEIPT="$(python3 -c '
import json,glob,sys
p = sorted(glob.glob(sys.argv[1] + "/.loki/proofs/*/proof.json"))[-1]
print(json.load(open(p)).get("run_id") or "")' "$D8S" 2>/dev/null)"
        if python3 -c '
import json, sys
d = json.load(open(sys.argv[1]))
want = sys.argv[2]
assert d.get("authorizing_run_id") == want, (d.get("authorizing_run_id"), want)
assert d.get("command"), "no command recorded"
assert d.get("exit_code") == 0, d.get("exit_code")
assert d.get("anchor_sha"), "no anchor recorded"
' "$REC" "$RUN_IN_RECEIPT" 2>/dev/null; then
            ok "deploy record names the command, exit code, anchor and authorizing run_id"
        else
            bad "deploy record is missing or does not name the authorizing run_id" "$(cat "$REC")"
        fi
    else
        bad "no deploy record written after an executed deploy"
    fi
else
    echo "  SKIPPED: no executed deploy to inspect (depends on test 8's signed path)"
fi

# ===========================================================================
# 9b. An UNEVALUABLE check refuses as UNCHECKED, and is NEVER reported as
#     TAMPERED. Both refuse, so the gate is safe either way -- but the WORDS
#     matter: TAMPERED is an accusation of forgery, and printing it for a check
#     that never ran sends the user hunting a tamper that did not happen and
#     trains them to shrug at a real one. Driven by shadowing python3 with a
#     binary that always fails, which is the honest "cannot evaluate" case.
# ===========================================================================
echo "9b. an unevaluable check refuses as UNCHECKED, never as TAMPERED"
D9B_BASE="$(make_fixture d9b)"; D9B="$WORKROOT/d9b"
gen_receipt "$D9B" "$D9B_BASE" >/dev/null
BROKEN_BIN="$WORKROOT/broken-bin"; mkdir -p "$BROKEN_BIN"
cp "$FAKE_BIN"/* "$BROKEN_BIN"/ 2>/dev/null || true
printf '#!/usr/bin/env bash\nexit 127\n' > "$BROKEN_BIN/python3"; chmod +x "$BROKEN_BIN/python3"
reset_sentinels
OUT9B="$( cd "$D9B" && PATH="$BROKEN_BIN:$PATH" LOKI_DIR="$D9B/.loki" \
    bash "$LOKI_BIN" deploy --dir "$D9B" --no-clip --execute 2>&1 )"
if [ "$(any_sentinel)" -eq 0 ] \
   && printf '%s' "$OUT9B" | grep -qi "REFUSED" \
   && printf '%s' "$OUT9B" | grep -qi "UNCHECKED" \
   && ! printf '%s' "$OUT9B" | grep -qi "TAMPERED"; then
    ok "a verifier that could not run reports UNCHECKED, not a forgery accusation"
else
    bad "an unevaluable check was reported as TAMPERED (or did not refuse)" \
        "sentinels=$(any_sentinel); $(printf '%s' "$OUT9B" | grep -i ' - ' | head -3)"
fi

# ===========================================================================
# 10. NON-VACUITY for test 1: the DEFAULT path must not deploy even a tree the
#     gate WOULD authorize. Test 1 alone cannot prove this -- its fixture is
#     unsigned, so the gate refuses anyway and an --execute flag that leaked
#     into the default path stays invisible. Measured: removing the
#     `do_execute` condition left test 1 green. Re-run against the SIGNED
#     fixture, where the only thing standing between it and a deploy is the
#     absence of --execute.
# ===========================================================================
echo "10. the default path does not deploy even a VERIFIED tree"
if [ -n "${D8S:-}" ] && [ "${D8S_EXECUTED:-0}" = "1" ]; then
    reset_sentinels
    OUT10="$( cd "$D8S" && PATH="$FAKE_BIN:$PATH" LOKI_DIR="$D8S/.loki" GNUPGHOME="${GNUPGHOME:-}" \
        bash "$LOKI_BIN" deploy --dir "$D8S" --no-clip 2>&1 )"
    if [ "$(any_sentinel)" -eq 0 ] && ! printf '%s' "$OUT10" | grep -qi "gate PASSED"; then
        ok "opt-in is per-invocation: no --execute, no deploy, even when authorized"
    else
        bad "the default path deployed -- --execute is not gating anything" \
            "sentinels=$(any_sentinel)"
    fi
else
    echo "  SKIPPED: needs test 8's signed fixture (not a pass)"
fi

# ===========================================================================
# 11-13. THE ANCHOR OVERRIDE.
#
# WHY IT EXISTS: measured on this repository, 8 of 9 receipts record no
# base_sha and the 9th records the empty tree, so the anchor check refused
# ~89% of real receipts. A gate that always refuses teaches users to route
# around it, and then the bypass becomes the default path.
#
# THE DISTINCTION, and it is the whole design:
#   UNANCHORED  no baseline recorded. Neither match nor mismatch can be
#               proven. Refuse by default, overridable, record that nothing
#               was proven.
#   MISMATCH    a baseline IS recorded and resolves elsewhere. Positive
#               evidence of the wrong build. The override must NOT bypass it.
#
# Test 13 is the load-bearing one: without it, --allow-unanchored silently
# degrades into "skip the anchor check entirely".
#
# These use the SIGNED fixture. Against an unsigned receipt the gate refuses on
# UNSIGNED too, so an override that did nothing would be indistinguishable from
# one that worked.
# ===========================================================================
echo "11-13. the anchor override covers UNKNOWN, never KNOWN WRONG"
if [ -n "${KEYID:-}" ] && [ "${D8S_EXECUTED:-0}" = "1" ]; then
    # Build a signed fixture whose receipt records NO baseline. Empty
    # _LOKI_RUN_START_SHA is exactly how the 8 real unanchored receipts arose.
    mk_signed() {  # <name> <base-sha-for-generator>
        # Split: under `set -u`, referencing $n inside the SAME `local`
        # statement that declares it reads an unbound variable.
        local n="$1" b="${2:-}"
        local bd="$WORKROOT/$n"
        make_fixture "$n" >/dev/null
        ( cd "$bd" && _LOKI_RUN_START_SHA="$b" \
            LOKI_PROOF_GPG_KEY="$KEYID" GNUPGHOME="$GNUPGHOME" \
            python3 "$GENERATOR" --loki-dir "$bd/.loki" >/dev/null 2>&1 )
    }
    run_signed() {  # <dir> [flags...]
        local d="$1"; shift
        ( cd "$d" && PATH="$FAKE_BIN:$PATH" LOKI_DIR="$d/.loki" GNUPGHOME="$GNUPGHOME" \
            bash "$LOKI_BIN" deploy --dir "$d" --no-clip "$@" 2>&1 )
    }

    mk_signed d11 ""
    D11="$WORKROOT/d11"

    # --- 11. unanchored refuses BY DEFAULT, and names anchoring as unproven ---
    reset_sentinels
    OUT11="$(run_signed "$D11" --execute)"
    if [ "$(any_sentinel)" -eq 0 ] \
       && printf '%s' "$OUT11" | grep -qi "REFUSED" \
       && printf '%s' "$OUT11" | grep -qi "records no baseline" \
       && printf '%s' "$OUT11" | grep -q -- "--allow-unanchored"; then
        ok "unanchored refuses by default and names the override"
    else
        bad "unanchored did not refuse, or did not say why" \
            "$(printf '%s' "$OUT11" | grep -i ' - ' | head -3)"
    fi

    # --- 12. the SAME receipt passes WITH the flag, and the record says so ---
    reset_sentinels
    OUT12="$(run_signed "$D11" --execute --allow-unanchored)"
    if [ "$(any_sentinel)" -ge 1 ] && printf '%s' "$OUT12" | grep -qi "gate PASSED"; then
        ok "--allow-unanchored lets the same receipt through"
    else
        bad "the override did not admit an unanchored receipt" \
            "$(printf '%s' "$OUT12" | grep -i ' - ' | head -3)"
    fi
    # The banner must NOT claim the tree was verified, and the RECORD must state
    # that the anchor was unproven. A deploy that logs itself as fully anchored
    # when it was overridden is a false green written to disk.
    if printf '%s' "$OUT12" | grep -qi "UNPROVEN" \
       && ! printf '%s' "$OUT12" | grep -qi "VERIFIED this tree"; then
        ok "the banner says the anchor was unproven, not that the tree was verified"
    else
        bad "an overridden deploy reported itself as fully verified" "$OUT12"
    fi
    REC12="$(ls -1t "$D11"/.loki/deploys/*.json 2>/dev/null | head -1)"
    if [ -n "$REC12" ] && python3 -c "
import json,sys
d=json.load(open(sys.argv[1]))
sys.exit(0 if d.get('anchor_state')=='unanchored_overridden'
            and d.get('anchor_proven') is False else 1)" "$REC12" 2>/dev/null; then
        ok "the deploy record states the anchor was unproven (overridden)"
    else
        bad "the deploy record does not distinguish overridden from anchored" \
            "$(cat "$REC12" 2>/dev/null | head -12)"
    fi
    # POSITIVE CONTROL for the record field: a genuinely anchored deploy must
    # record anchored/true. Without this, "records overridden" could pass by
    # writing that value unconditionally.
    REC8="$(ls -1t "$D8S"/.loki/deploys/*.json 2>/dev/null | head -1)"
    if [ -n "$REC8" ] && python3 -c "
import json,sys
d=json.load(open(sys.argv[1]))
sys.exit(0 if d.get('anchor_state')=='anchored'
            and d.get('anchor_proven') is True else 1)" "$REC8" 2>/dev/null; then
        ok "POSITIVE CONTROL: a genuinely anchored deploy records anchored/proven"
    else
        bad "an anchored deploy did not record itself as anchored" \
            "$(cat "$REC8" 2>/dev/null | head -12)"
    fi

    # The marker the gate uses to carry "unproven" across the $( ) boundary is
    # an INTERNAL token. If a future edit moves the strip after the emptiness
    # test, the user is shown "__LOKI_ANCHOR_UNPROVEN__" as a refusal reason.
    if printf '%s' "$OUT12" | grep -q "__LOKI_ANCHOR_UNPROVEN__" \
       || printf '%s' "$OUT11" | grep -q "__LOKI_ANCHOR_UNPROVEN__"; then
        bad "the internal anchor marker leaked into user-facing output"
    else
        ok "the internal marker never reaches the user, on either path"
    fi

    # --- 12c. UNANCHORED + a REAL reason: strip one, keep the other --------
    # The ONLY path where `reasons` carries the marker AND a genuine refusal.
    # It is what the newline-stripping exists for: remove the marker without
    # joining or swallowing the real reason. Test 12's fixture is clean, so
    # this branch would otherwise never execute.
    # TWO real reasons alongside the marker, so the joined-vs-separate
    # distinction is observable: a dirty tree AND an untracked second file are
    # both counted by _deploy_tree_clean, so instead we take the dirty tree plus
    # an UNSIGNED receipt (generated without the key) -- two distinct lines.
    make_fixture d12c >/dev/null; D12C="$WORKROOT/d12c"
    ( cd "$D12C" && _LOKI_RUN_START_SHA="" \
        python3 "$GENERATOR" --loki-dir "$D12C/.loki" >/dev/null 2>&1 )
    printf 'dirty\n' >> "$D12C/package.json"    # dirty + unsigned + unanchored
    reset_sentinels
    OUT12C="$(run_signed "$D12C" --execute --allow-unanchored)"
    if [ "$(any_sentinel)" -eq 0 ] \
       && printf '%s' "$OUT12C" | grep -qi "REFUSED" \
       && printf '%s' "$OUT12C" | grep -qi "dirty" \
       && ! printf '%s' "$OUT12C" | grep -q "__LOKI_ANCHOR_UNPROVEN__"; then
        ok "override + a real reason: the marker is stripped, the reason survives"
    else
        bad "stripping the marker lost or mangled a co-occurring refusal reason" \
            "$(printf '%s' "$OUT12C" | grep -i ' - ' | head -3)"
    fi
    # Reasons must stay one PER LINE. MEASURED: stripping with `tr -d '\n'`
    # collapses two reasons into one line -- and a grep for either substring
    # still matches, so only counting the lines detects it. This tree is dirty
    # AND unsigned, so two reasons are expected.
    if [ "$(printf '%s\n' "$OUT12C" | grep -c '^  - ')" -ge 2 ]; then
        ok "co-occurring reasons stay one per line (not joined into one)"
    else
        bad "multiple refusal reasons were joined onto a single line" \
            "$(printf '%s\n' "$OUT12C" | grep '^  - ' | head -3)"
    fi

    # --- 12b. an AMBIENT env var must not opt in ---------------------------
    # The help text promises "no env var or config file alone can opt in", and
    # the flag is implemented by setting a variable the gate reads -- so an
    # exported LOKI_DEPLOY_ALLOW_UNANCHORED=true would silently weaken the gate
    # for every deploy in that shell. cmd_deploy declares it `local`; this is
    # what proves that declaration is load-bearing.
    reset_sentinels
    OUT12B="$( cd "$D11" && PATH="$FAKE_BIN:$PATH" LOKI_DIR="$D11/.loki" GNUPGHOME="$GNUPGHOME" \
        LOKI_DEPLOY_ALLOW_UNANCHORED=true \
        bash "$LOKI_BIN" deploy --dir "$D11" --no-clip --execute 2>&1 )"
    if [ "$(any_sentinel)" -eq 0 ] && printf '%s' "$OUT12B" | grep -qi "REFUSED"; then
        ok "an ambient env var alone does NOT opt in (the flag is per-invocation)"
    else
        bad "an exported env var weakened the gate without the flag" \
            "sentinels=$(any_sentinel)"
    fi

    # --- 13. LOAD-BEARING: a MISMATCH still refuses WITH the flag set -------
    # Stale-head mismatch: the receipt anchors, then the tree advances past it.
    # resolve_anchor still returns "anchored" (it answers "can I follow this
    # receipt", not "is this the tree I am shipping"), so the stale-head branch
    # is what refuses. That branch must stay unreachable from the override.
    D13_BASE="$(make_fixture d13)"; D13="$WORKROOT/d13"
    ( cd "$D13" && _LOKI_RUN_START_SHA="$D13_BASE" \
        LOKI_PROOF_GPG_KEY="$KEYID" GNUPGHOME="$GNUPGHOME" \
        python3 "$GENERATOR" --loki-dir "$D13/.loki" >/dev/null 2>&1 )
    echo "// advanced past the receipt" >> "$D13/package.json"
    git -C "$D13" add package.json
    git -C "$D13" commit -qm "advance past the receipt"
    reset_sentinels
    OUT13="$(run_signed "$D13" --execute --allow-unanchored)"
    if [ "$(any_sentinel)" -eq 0 ] && printf '%s' "$OUT13" | grep -qi "REFUSED"; then
        ok "a MISMATCH still refuses WITH --allow-unanchored (override is not a skip)"
    else
        bad "--allow-unanchored bypassed a recorded mismatch -- it became skip-the-check" \
            "sentinels=$(any_sentinel); $(printf '%s' "$OUT13" | grep -i ' - ' | head -3)"
    fi
    # And it must refuse for the RIGHT reason: naming the mismatch, not silently
    # failing on something unrelated that would mask a broken override.
    if printf '%s' "$OUT13" | grep -qiE "different commit|does not anchor"; then
        ok "the mismatch refusal names the anchor mismatch as the cause"
    else
        bad "the mismatch refusal did not name anchoring" \
            "$(printf '%s' "$OUT13" | grep -i ' - ' | head -3)"
    fi
else
    echo "  SKIPPED: needs gpg and test 8's signed fixture (not a pass)"
fi

echo ""
echo "==================================================================="
echo "Passed: $PASS   Failed: $FAIL"
[ "$FAIL" -eq 0 ] || exit 1
exit 0
