#!/usr/bin/env bash
# The first artifact a user sees must not lie about the product or the user.
#
# TWO DEFECTS, both on the headline `loki start owner/repo#123` path:
#  1. `- Generated by: Loki Mode CLI v6.0.0` was a hardcoded literal. It printed
#     on a v9.44.0 install: three majors stale. A product whose entire pitch is
#     a verifiable receipt cannot misreport its own version in the first
#     document it generates.
#  2. Acceptance Criteria were generic filler ("Address all requirements
#     specified in the issue body above"). A user who HAD enumerated their
#     requirements got them rendered, then overridden by boilerplate in the
#     same document.
#
# WHAT IS LOAD-BEARING: extraction must not FABRICATE. When the issue body has
# no checklist, the generic list is correct output, and it must say so rather
# than presenting defaults as if they came from the user. Both directions are
# asserted.
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT" || exit 1

PASS=0; FAIL=0
pass() { PASS=$((PASS+1)); echo "  PASS: $1"; }
fail() { FAIL=$((FAIL+1)); echo "  FAIL: $1"; }

echo "test-issue-prd-is-honest"

if ! command -v python3 >/dev/null 2>&1; then
    fail "python3 unavailable: the PRD generator was NOT exercised (unmeasured)"
    echo "  $PASS passed, $FAIL failed"; exit 1
fi

# shellcheck disable=SC1091
source autonomy/issue-providers.sh 2>/dev/null || true
if ! declare -f generate_prd_from_issue >/dev/null 2>&1; then
    fail "generate_prd_from_issue is not defined; nothing was measured"
    echo "  $PASS passed, $FAIL failed"; exit 1
fi

VER="$(cat VERSION | tr -d '[:space:]')"

# 1-2. A body WITH a checklist: the user's own items must appear, and the
#      generic filler must NOT override them.
OUT_A="$(printf '%s' '{"provider":"github","number":"42","title":"Add dark mode","body":"Need it.\n\n- [ ] Toggle in settings\n- [ ] Persist the choice","labels":[],"author":"a","url":"u","created_at":"d","repo":"o/r"}' \
    | LOKI_VERSION="$VER" generate_prd_from_issue 2>/dev/null)"

if printf '%s' "$OUT_A" | grep -q 'Toggle in settings' && printf '%s' "$OUT_A" | grep -q 'Persist the choice'; then
    pass "a user's enumerated requirements reach the PRD"
else
    fail "the user's own requirements are missing from the generated PRD"
fi

if printf '%s' "$OUT_A" | grep -q 'Address all requirements specified in the issue body above'; then
    fail "generic filler still overrides a user who listed real requirements"
else
    pass "generic filler does not override real extracted requirements"
fi

# 3. The version must be the REAL one, never a hardcoded literal.
if printf '%s' "$OUT_A" | grep -q "Loki Mode CLI v${VER}"; then
    pass "the PRD reports the real version (v${VER})"
else
    fail "the PRD does not report v${VER}: $(printf '%s' "$OUT_A" | grep -a 'Generated by' || echo '(no version line)')"
fi

if printf '%s' "$OUT_A" | grep -q 'v6\.0\.0'; then
    fail "the hardcoded v6.0.0 literal is back"
else
    pass "no hardcoded version literal"
fi

# 4. NO FABRICATION. A body with no checklist must fall back AND say it is a
#    fallback, not present defaults as the user's own requirements.
OUT_B="$(printf '%s' '{"provider":"github","number":"7","title":"Bug","body":"It crashes sometimes.","labels":[],"author":"a","url":"u","created_at":"d","repo":"o/r"}' \
    | LOKI_VERSION="$VER" generate_prd_from_issue 2>/dev/null)"

if printf '%s' "$OUT_B" | grep -q 'no explicit checklist'; then
    pass "an issue without a checklist falls back AND labels the fallback"
else
    fail "the fallback does not disclose that these are defaults, not the user's items"
fi

if printf '%s' "$OUT_B" | grep -q 'Extracted from the issue body'; then
    fail "claims extraction on a body that has no checklist (fabrication)"
else
    pass "does not claim extraction when there was nothing to extract"
fi

# 5. GUARD AGAINST VACUITY: if the version were unset the generator says
#    "unknown", and every assertion above about v${VER} would be meaningless.
if [ -n "$VER" ]; then
    pass "VERSION is readable (so the version assertions mean something)"
else
    fail "VERSION unreadable; the version assertions are vacuous"
fi

echo "  $PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ]
