#!/bin/bash
#PBS -N iqtree_genes
#PBS -t 1-NUM_LOCI
#PBS -l nodes=1:ppn=1
#PBS -l mem=4gb
#PBS -l walltime=2:00:00

cd $PBS_O_WORKDIR/trimmed_aa
source ~/.bashrc
conda activate phylo

# Create list of alignments if not present
if [ ! -f locus_alignments.txt ]; then
    ls *_trimmed.fas > locus_alignments.txt
fi

locus=$(sed -n "${PBS_ARRAYID}p" locus_alignments.txt)

iqtree \
  -s ${locus} \
  -m MFP \
  -bb 1000 \
  -bnni \
  -czb \
  -pre $(basename ${locus} _trimmed.fas) \
  -nt 1
