#!/usr/bin/env node
// build-hosted — Reproducible hosted skill releases (EX-3049 / EX-3054).
//
// Each published version is materialized exclusively from its git tag. This
// keeps a dirty checkout (or files introduced after a release) from leaking
// into the hosted site, while the generated manifest makes every served byte
// independently verifiable.
//
// Usage:
//   node scripts/build-hosted.mjs --out <dir> [options]
//
// Options:
//   --out <dir>            Destination directory (required; wiped and recreated —
//                          must be new, empty, or a previous build-hosted output)
//   --repo <path>           Git repository to read (default: .)
//   --latest <tag>          Pin the unversioned site to a built vX.Y.Z tag
//   --min-version <semver>  Exclude older releases

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { buildManifest, compareVersions, releaseTags, skillTrees, treeHashAt } from './build-manifest.mjs';

function fail(message) {
  console.error(`build-hosted: ${message}`);
  process.exit(1);
}

function parseVersion(value) {
  const match = /^(\d+)\.(\d+)\.(\d+)$/.exec(value);
  return match ? match.slice(1).map(Number) : null;
}

function git(repo, args, options = {}) {
  return execFileSync('git', ['-C', repo, ...args], {
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
    ...options,
  }).trim();
}

function parseArgs(argv) {
  const options = { out: null, repo: '.', latest: null, minVersion: null };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === '--out') options.out = argv[++i];
    else if (arg === '--repo') options.repo = argv[++i];
    else if (arg === '--latest') options.latest = argv[++i];
    else if (arg === '--min-version') options.minVersion = argv[++i];
    else fail(`unknown argument: ${arg}`);
  }
  if (!options.out) fail('--out <dir> is required');
  if (options.latest && !/^v\d+\.\d+\.\d+$/.test(options.latest)) {
    fail(`--latest must be a vMAJOR.MINOR.PATCH tag (got ${JSON.stringify(options.latest)})`);
  }
  if (options.minVersion && !parseVersion(options.minVersion)) {
    fail(`--min-version must be MAJOR.MINOR.PATCH (got ${JSON.stringify(options.minVersion)})`);
  }
  return options;
}

function archiveTag(repo, tag, destination) {
  const candidates = ['skills', '.ctx-gen', 'package.json', 'skill-registry.json'];
  const paths = candidates.filter((candidate) => git(repo, ['ls-tree', '--name-only', tag, '--', candidate]));
  if (!paths.length) return;
  const archive = path.join(destination, 'release.tar');
  execFileSync('git', ['-C', repo, 'archive', '--format=tar', `--output=${archive}`, tag, ...paths], {
    stdio: ['ignore', 'ignore', 'pipe'],
  });
  execFileSync('tar', ['-xf', archive, '-C', destination]);
  fs.rmSync(archive);
}

// The output directory is wiped before every build, so `--out` must never
// point at something we did not generate: the repo, an ancestor of it, the
// filesystem root, or any non-empty directory without our marker file.
const MARKER = '.build-hosted';

function guardOutput(output, repo) {
  const isAncestorOrSelf = (dir, target) => target === dir || target.startsWith(dir + path.sep);
  if (output === path.parse(output).root) throw new Error(`--out ${output}: refusing to use a filesystem root`);
  if (isAncestorOrSelf(output, repo)) throw new Error(`--out ${output}: refusing to wipe the repository or one of its ancestors`);
  if (isAncestorOrSelf(output, process.cwd())) throw new Error(`--out ${output}: refusing to wipe the current directory or one of its ancestors`);
  const stat = fs.lstatSync(output, { throwIfNoEntry: false });
  if (!stat) return;
  if (!stat.isDirectory()) throw new Error(`--out ${output}: exists and is not a directory`);
  if (fs.readdirSync(output).length && !fs.existsSync(path.join(output, MARKER))) {
    throw new Error(`--out ${output}: is not empty and was not generated by build-hosted (no ${MARKER} marker); refusing to wipe it`);
  }
}

function hasSkills(repo, tag) {
  const tree = git(repo, ['ls-tree', '-r', '--name-only', tag, '--', 'skills']);
  return tree.split('\n').some((file) => /^skills\/netlify-[^/]+\/SKILL\.md$/.test(file));
}

function copyManifestSkills(root, destination, manifest) {
  for (const skill of manifest.skills) {
    if (skill.status !== 'active') continue;
    for (const relative of Object.keys(skill.files)) {
      const target = path.join(destination, 'skills', skill.name, ...relative.split('/'));
      fs.mkdirSync(path.dirname(target), { recursive: true });
      fs.copyFileSync(path.join(root, 'skills', skill.name, ...relative.split('/')), target);
    }
  }
}

function htmlEscape(value) {
  return value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
}

function indexHtml(manifest) {
  const items = manifest.skills
    .filter(({ status }) => status === 'active')
    .map(({ name }) => `      <li><a href="skills/${encodeURIComponent(name)}/SKILL.md">${htmlEscape(name)}</a></li>`)
    .join('\n');
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Netlify skills</title>
    <style>body { font-family: system-ui, sans-serif; max-width: 48rem; margin: 3rem auto; padding: 0 1rem; }</style>
  </head>
  <body>
    <h1>Netlify skills</h1>
    <p>Versioned, verifiable skills for agents building on Netlify. See the <a href="manifest.json">manifest</a> or <a href="versions.json">available versions</a>.</p>
    <ul>
${items}
    </ul>
  </body>
</html>
`;
}

export function buildHosted({ out, repo = '.', latest = null, minVersion = null }) {
  const repoPath = path.resolve(repo);
  let tags;
  try {
    tags = releaseTags(repoPath)
      .filter((tag) => !minVersion || compareVersions(tag.slice(1), minVersion) >= 0)
      .filter((tag) => hasSkills(repoPath, tag));
  } catch (error) {
    throw new Error(`cannot read git tags: ${error.stderr?.toString().trim() || error.message}`);
  }
  if (!tags.length) throw new Error('no eligible version tags contain skills');
  if (latest && !tags.includes(latest)) throw new Error(`--latest ${latest} is not one of the built tags`);

  const output = path.resolve(out);
  guardOutput(output, repoPath);
  fs.rmSync(output, { recursive: true, force: true });
  fs.mkdirSync(output, { recursive: true });
  fs.writeFileSync(path.join(output, MARKER), 'generated by scripts/build-hosted.mjs; safe to delete\n');
  const manifests = new Map();
  // Per-skill versions for tag N depend on every release tag before it (not
  // only those with skills, and regardless of --min-version), so the history
  // walk uses the full tag list and reuses each tag's skill trees.
  const history = releaseTags(repoPath).map((tag) => ({ version: tag.slice(1), trees: skillTrees(repoPath, tag) }));
  // A skill's tree_hash at a given tag is the same whichever manifest asks.
  const hashed = new Map();
  const hashAt = (version, name) => {
    const key = `${version}\0${name}`;
    if (!hashed.has(key)) hashed.set(key, treeHashAt(repoPath, `v${version}`, name));
    return hashed.get(key);
  };

  for (const tag of tags) {
    const temporary = fs.mkdtempSync(path.join(os.tmpdir(), 'build-hosted-'));
    try {
      archiveTag(repoPath, tag, temporary);
      const commit = git(repoPath, ['rev-list', '-n', '1', tag]);
      const date = git(repoPath, ['log', '-1', '--format=%cI', commit]);
      const publishedAt = new Date(date).toISOString().replace('.000Z', 'Z');
      const version = tag.slice(1);
      const manifest = buildManifest({
        root: temporary, version, commit, publishedAt,
        history: { repo: repoPath, hashAt, tags: history.filter((entry) => compareVersions(entry.version, version) < 0) },
      });
      const versionRoot = path.join(output, 'v', tag.slice(1));
      fs.mkdirSync(versionRoot, { recursive: true });
      fs.writeFileSync(path.join(versionRoot, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);
      copyManifestSkills(temporary, versionRoot, manifest);
      manifests.set(tag, manifest);
      console.log(`[built] ${tag}: ${manifest.skills.filter(({ status }) => status === 'active').length} active skills`);
    } finally {
      fs.rmSync(temporary, { recursive: true, force: true });
    }
  }

  const latestTag = latest || tags.at(-1);
  const latestVersion = latestTag.slice(1);
  const latestRoot = path.join(output, 'v', latestVersion);
  fs.copyFileSync(path.join(latestRoot, 'manifest.json'), path.join(output, 'manifest.json'));
  fs.cpSync(path.join(latestRoot, 'skills'), path.join(output, 'skills'), { recursive: true });
  fs.writeFileSync(path.join(output, 'versions.json'), `${JSON.stringify({
    schema_version: 1,
    latest: latestVersion,
    versions: tags.map((tag) => tag.slice(1)),
  }, null, 2)}\n`);
  fs.writeFileSync(path.join(output, 'index.html'), indexHtml(manifests.get(latestTag)));
  console.log(`[done] ${tags.length} versions; latest ${latestTag}`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const options = parseArgs(process.argv.slice(2));
  try {
    buildHosted(options);
  } catch (error) {
    fail(error.message);
  }
}
