#!/bin/bash
#SBATCH --job-name=iqtree_partition
#SBATCH --cpus-per-task=18
#SBATCH --mem-per-cpu=4G
#SBATCH --time=72:00:00
#SBATCH --output=logs/partition_search.out
#SBATCH --error=logs/partition_search.err

source ~/.bashrc
conda activate phylo

cd 06_concatenation  # Use organized directory structure

iqtree \
  -s FcC_supermatrix.fas \
  -spp partition_def.txt \
  -nt ${SLURM_CPUS_PER_TASK} \
  -safe \
  -pre partition_search \
  -m TESTMERGEONLY \
  -mset MODEL_SET \
  -msub nuclear \
  -rcluster 10 \
  -bb 1000 \
  -alrt 1000

# Output: partition_search.best_scheme.nex
