#!/bin/bash
#SBATCH --job-name=iqtree_genes
#SBATCH --array=1-NUM_LOCI
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=4G
#SBATCH --time=2:00:00
#SBATCH --output=logs/%A_%a.genetree.out

source ~/.bashrc
conda activate phylo

cd trimmed_aa

# Create list of alignments if not present
if [ ! -f locus_alignments.txt ]; then
    ls *_trimmed.fas > locus_alignments.txt
fi

locus=$(sed -n "${SLURM_ARRAY_TASK_ID}p" locus_alignments.txt)

iqtree \
  -s ${locus} \
  -m MFP \
  -bb 1000 \
  -bnni \
  -czb \
  -pre $(basename ${locus} _trimmed.fas) \
  -nt 1
